Repository GSG-G8/tetris, pull requests merged in 2020-04, with the labels that each got.

#2 1 setup project
  .eslintrc.js
  README.md
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/assets/images/jeremy-bishop-G9i_plbfDgk-unsplash.jpg
  src/components/index.js
  src/hooks/index.js
  src/index.js
  src/logo.svg
  src/serviceWorker.js
Labels: Awaiting Review

#4 readme
  README.md
Labels: Done

#8 7 create components
  package.json
  src/App.js
  src/components/Cell/index.js
  src/components/Display/index.js
  src/components/Stage/index.js
  src/components/StartButton/index.js
  src/components/Tetris/index.js
Labels: Awaiting Review, Front-End

#9 5 game helpers
  src/utils/createStage.js
Labels: Awaiting Review

#11 create tetrominos
  src/utils/tetrominos.js
Labels: Awaiting Review, Front-End

#14 10 primary style
  .eslintrc.js
  src/App.css
  src/components/Cell/index.js
  src/components/Cell/style.css
  src/components/Display/index.js
  src/components/Display/style.css
  src/components/Stage/index.js
  src/components/Stage/style.css
  src/components/StartButton/index.js
  src/components/Tetris/index.js
  src/components/Tetris/style.css
Labels: Awaiting Review

#13 create usePlayer custom hook
  src/hooks/usePlayer.js
Labels: Awaiting Review, Front-End

#17 custom hooks in tetris file
  src/components/Display/index.js
  src/components/Stage/index.js
  src/components/Tetris/index.js
  src/hooks/usePlayer.js
Labels: Awaiting Review, Front-End

#20 18 use player
  .eslintrc.js
  src/hooks/usePlayer.js
Labels: Awaiting Review

#21 19 update stage
  src/hooks/usePlayer.js
  src/hooks/useStage.js
Labels: Awaiting Review, Front-End
